version: '3'
services:
  web:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5000:8080"
    volumes:
      - ./backend:/usr/src/app/
  db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: "db"
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data